apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "plex.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "plex.name" . }}
    spec:
      containers:
      - name: plex
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: plex-web
          containerPort: 32400
          protocol: TCP
        - name: dlna-tcp
          containerPort: 32469
          protocol: TCP
        - name: dlna-udp
          containerPort: 1900
          protocol: UDP
        - name: bonjour-udp
          containerPort: 5353
          protocol: UDP
        - name: roku
          containerPort: 8324
          protocol: TCP
        - name: gdm-1
          containerPort: 32410
          protocol: UDP
        - name: gdm-2
          containerPort: 32412
          protocol: UDP
        - name: gdm-3
          containerPort: 32413
          protocol: UDP
        - name: gdm-4
          containerPort: 32414
          protocol: UDP
        env:
        - name: TZ
          value: {{ .Values.env.TZ | quote }}
        - name: ADVERTISE_IP
          value: {{ .Values.env.ADVERTISE_IP | quote }}
        - name: PLEX_UID
          value: {{ .Values.env.PLEX_UID | quote }}
        - name: PLEX_GID
          value: {{ .Values.env.PLEX_GID | quote }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: transcode
          mountPath: /transcode
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
      - name: media
        persistentVolumeClaim:
          claimName: plex-media
      - name: transcode
        persistentVolumeClaim:
          claimName: plex-transcode
