apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  selector:
    app: {{ include "plex.name" . }}
  ports:
  - name: plex-web
    port: {{ .Values.service.port }}
    targetPort: 32400
    {{- if eq .Values.service.type "NodePort" "LoadBalancer" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: TCP
