apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overseerr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "overseerr.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "overseerr.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "overseerr.name" . }}
    spec:
      containers:
      - name: overseerr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: web
          containerPort: 5055
        env:
        - name: TZ
          value: {{ .Values.env.TZ | quote }}
        volumeMounts:
        - name: config
          mountPath: /app/config
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: overseerr-config
