# Default values for Overseerr chart

namespace: media

image:
  repository: sctx/overseerr
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: "UTC"

service:
  type: NodePort
  port: 5055
  nodePort: 32055

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

storage:
  storageClass: standard
  config:
    size: 5Gi
    accessModes:
      - ReadWriteOnce
