apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tautulli.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tautulli.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "tautulli.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tautulli.name" . }}
    spec:
      containers:
      - name: tautulli
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: web
          containerPort: 8181
        env:
        - name: TZ
          value: {{ .Values.env.TZ | quote }}
        - name: PUID
          value: {{ .Values.env.PUID | quote }}
        - name: PGID
          value: {{ .Values.env.PGID | quote }}
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tautulli-config
