apiVersion: v1
kind: Service
metadata:
  name: {{ include "tautulli.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tautulli.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  selector:
    app: {{ include "tautulli.name" . }}
  ports:
  - name: web
    port: {{ .Values.service.port }}
    targetPort: 8181
    {{- if eq .Values.service.type "NodePort" "LoadBalancer" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
